#!/bin/sh

warning() {
  echo "\\e[1;33m$1"
}

if make lint
then
  exit 0
else
  warning "One or more linter checks are failing."
  warning "Please fix those checks before pushing your changes."
  exit 1
fi
