site_name: Maker Regular Expression
site_url: https://github.com/alvarofpp/mre
site_description: This a simple package to make regular expression in Python.
site_author: MkDocs Team

nav:
  - Home: index.md
  - 'da-DK': da_DK/
  - 'de-DE': de_DE/
  - 'en-US': en_US/
  - 'es-ES': es_ES/
  - 'pt-BR': pt_BR/
  - 'ru-RU': ru_RU/
  - 'uk-UA': uk_UA/
  - License: licenca.md

repo_url: https://github.com/alvarofpp/mre

theme: readthedocs
