site_name: Maker Regular Expression
site_url: https://github.com/alvarofpp/mre
site_description: This a simple package to make regular expression in Python.
site_author: MkDocs Team

nav:
  - Home: index.md
  - 'de': de/
  - 'dk': dk/
  - 'en': en_US/
  - 'es-ES': es_ES/
  - 'pt-BR': pt_BR/
  - 'uk-UA': uk_UA/
  - License: licenca.md

repo_url: https://github.com/alvarofpp/mre

theme: readthedocs
